#!/bin/bash

# Extraction dynamique de la version depuis pyproject.toml
VERSION=$(grep -E '^version\s*=' ../pyproject.toml | head -n 1 | sed -E 's/version\s*=\s*"(.*)"/\1/')

echo "🎉 Bienvenue dans OpenStack Toolbox 🧰 v$VERSION 🎉"

cat << "EOF"
  ___                       _             _       
 / _ \ _ __   ___ _ __  ___| |_ __ _  ___| | __   
| | | | '_ \ / _ \ '_ \/ __| __/ _` |/ __| |/ /   
| |_| | |_) |  __/ | | \__ \ || (_| | (__|   <    
 \___/| .__/ \___|_| |_|___/\__\__,_|\___|_|\_\   
/ ___||_|  _ _ __ ___  _ __ ___   __ _ _ __ _   _ 
\___ \| | | | '_ ` _ \| '_ ` _ \ / _` | '__| | | |
 ___) | |_| | | | | | | | | | | | (_| | |  | |_| |
|____/ \__,_|_| |_| |_|_| |_| |_|\__,_|_|   \__, |
                                            |___/ 
            By Loutre

EOF

