#!/bin/bash

# Extraction dynamique de la version depuis pyproject.toml
VERSION=$(grep -E '^version\s*=' ../pyproject.toml | head -n 1 | sed -E 's/version\s*=\s*"(.*)"/\1/')

if [ $# -eq 0 ]; then

  cat << "EOF"
  ___                       _             _    
 / _ \ _ __   ___ _ __  ___| |_ __ _  ___| | __
| | | | '_ \ / _ \ '_ \/ __| __/ _` |/ __| |/ /
| |_| | |_) |  __/ | | \__ \ || (_| | (__|   < 
 \___/| .__/ \___|_| |_|___/\__\__,_|\___|_|\_\
|_   _|_|   ___ | | |__   _____  __            
  | |/ _ \ / _ \| | '_ \ / _ \ \/ /            
  | | (_) | (_) | | |_) | (_) >  <             
  |_|\___/ \___/|_|_.__/ \___/_/\_\            
            By Loutre

EOF

  echo -e "\n🧰 OpenStack Toolbox (v$VERSION)"
  echo "Commandes disponibles :"
  echo "  • openstack-summary      → Génère un résumé global du projet"
  echo "  • openstack-optimization → Identifie les ressources sous-utilisées dans la semaine"
  echo "  • weekly-notification    → Paramètre l'envoi d'un e-mail avec le résumé de la semaine"
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Rendre tous les fichiers du dossier scripts exécutables
find "$SCRIPT_DIR" -type f -exec chmod +x {} \;

case "$1" in
  openstack-summary)
    "$SCRIPT_DIR/openstack-summary"
    ;;
  openstack-optimization)
    "$SCRIPT_DIR/openstack-optimization"
    ;;
  weekly-notification)
    "$SCRIPT_DIR/weekly-notification"
    ;;
  *)
    echo "❌ Commande inconnue : $1"
    echo "Utilisation : $0 {openstack-summary|openstack-optimization|weekly-notification}"
    exit 1
    ;;
esac